---
- hosts: 172.31.0.77
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name : create folder 
    file :
      path : /home/ubuntu/myfolder 
      state :  directory

  - name : copy file form master to node 
    copy : 
      src : my2ndfile.txt 
      dest : /home/ubuntu/my2ndfile.txt     