---
- name : copy tomcat user file into ansible node side 
  template :
     src: Template/mytomcatuser.j2
     dest : sudo nano /opt/tomcat/conf/tomcat-users.xml
- name : copy context file into node side 
  template : 
     src : Template/mycontext.j2  
     dest : sudo nano /opt/tomcat/webapps/manager/META-INF/context.xml

- name : copy host context file into node side 
  template : 
     src : Template/myhostcontext.j2
     dest : sudo nano /opt/tomcat/webapps/host-manager/META-INF/context.xml

- name : copy tomcat service file into node side 
  template : 
     src : Template/mytomservice.j2 
     dest :  sudo nano /etc/systemd/system/tomcat.service